### ISSUE TITLE
Pin SSH-Key

### ISSUE THREAD

**Issue by t2d** [bfmartin/ansible-sshknownhosts-role#6]
I think it would be a nice idea to pin specific ssh-keys. If I'm really certain, that I want only one key, I could provide it's fingerprint instead of using sshkeyscan.
```
ssh_known_hosts:
  - name: srv.example.org
    fingerprint: AAAAE2VjZHNhLXNoYTItbmlzdHAyN...
    aliases:
      - srv

**Comment by bfmartin** [comment]
Hi.

Thank you for raising this. I have thought about this already but have not been able to decide. There is a built-in Ansible module that does something similar. Here:

https://docs.ansible.com/ansible/latest/known_hosts_module.html

Have you looked at it? Does it already do what you suggest? Or something close? I would like to figure out if the built-in is sufficient or deficient before merging the PR.

Thank you.

**Comment by t2d** [comment]
actually, the known_hosts module would be a good place for this, but it doesn't support using aliases by now. also, there are some strange issues like https://github.com/ansible/ansible/issues/29319

**Comment by bfmartin** [comment]
Merged! Thank you.
